name: lighning_start
description: Starter Project for Lightning Dart
version: 2.0.2
author: Accorto Lightning <lightning@accorto.com>
homepage: http://lightningdart.com

environment:
  sdk: '>=1.17.0'

dependencies:
  lightning:
    git: git://github.com/accorto/lightning-dart.git # latest

dev_dependencies:
  test: '>=0.12.14'
